version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes_password
      POSTGRES_DB: hermes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hermes"]
      interval: 5s
      timeout: 5s
      retries: 5

  hermes:
    build: .
    ports:
      - "8000:8000"
      - "2525:2525"
    environment:
      DATABASE_URL: postgresql://hermes:hermes_password@postgres:5432/hermes
      SMTP_HOST: 0.0.0.0
      SMTP_PORT: 2525
      SMTP_DOMAIN: localhost
      API_KEY: your-secure-api-key-here
      DKIM_PRIVATE_KEY_PATH: /app/dkim/private.key
      DKIM_SELECTOR: default
    volumes:
      - ./dkim:/app/dkim
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: